@base_url = http://localhost:8000/api/brawler

### register
POST  http://127.0.0.1:8000/api/brawler/register
Content-Type: application/json

{
    "username": "test_brawler",
    "password": "securepassword"
}
